# Data configuration
ami_set: /home/ubuntu/Multichannel_dia/experiment5
noise: /home/ubuntu/Multichannel_dia/datasets/free-sound/
ckpt_path : C:/projects/experiment_1/checkpoints/epoch=236-Segmentation-AMISpeakerDiarizationonly_words-DiarizationErrorRate=0.184057.ckpt
json: /home/ubuntu/Multichannel_dia/experiment5/stats_stereo.json
sample_rate: 16000
# Number of channels in the simulated room (must match IR dataset and >= 2)
num_channels: 2
# Number of speakers for diarization AND separation (<= num_spatial_sources)
num_speakers: 4
num_sources: 4
# Duration of an input chunk in seconds
chunk_duration: 5.0
noise_min_snr: 5.0
noise_max_snr: 15.0
noise_probability: 0.9

fft_size: 128
hidden_size: 128
num_layers: 4
dropout: 0.5
ssep_loss_target_channel: spec_mean
learning_rate: 0.001
batch_size: 32
epochs: 300
loss_weight: 0.5
channels_choice: first
step: 0.5

