# Data configuration
ami_set: /gpfswork/rech/cjx/uaf42iq/multichannel-dia/PyanNet_v1/PyanNet
noise: /gpfswork/rech/cjx/uaf42iq/datasets/free-sound/

# Duration of an input chunk in seconds
chunk_duration: 5.0
noise_min_snr: 5.0
noise_max_snr: 15.0
noise_probability: 0.9

learning_rate: 0.001
batch_size: 32
epochs: 300
step: 0.5
